# Generated by Django 3.1.7 on 2021-03-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_checkout_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
